eureka:
  client:
    register-with-eureka: false

server:
  port: 8111

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/student/**
        - id: school
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/school/**


